version: '3.9'

services:
  nginx:
    image: openresty/openresty
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    
    volume:
        - ./data/nginx.conf:/etc/openresty/nginx.conf
        - ./data/default.conf:/etc/nginx/conf.d/default.conf
