version: "3.8"
services:
  apache:
    image: openresty/openresty
    ports:
      - 80:80
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003

    volumes:
      - ./data/nginx.conf:/etc/openresty/nginx.conf
      - ./data/default.conf:/etc/nginx/conf.d/default.conf

    # restart: always
